function svgPlaceholder(text: string, w = 640, h = 360, bg = "1a1a2e", fg = "dc2626"): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
    <rect fill="#${bg}" width="${w}" height="${h}"/>
    <text x="50%" y="50%" text-anchor="middle" dominant-baseline="middle" fill="#${fg}" font-family="Inter,system-ui,sans-serif" font-size="${Math.min(w, h) * 0.12}" font-weight="800">${text}</text>
  </svg>`;
  const base64 = typeof btoa === 'function' ? btoa(svg) : Buffer.from(svg).toString('base64');
  return `data:image/svg+xml;base64,${base64}`;
}

export const postIds = {
  p1: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
  p2: "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d",
  p3: "550e8400-e29b-41d4-a716-446655440000",
  p4: "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
  p5: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
};

export const projectIds = {
  pr1: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
  pr2: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
  pr3: "c3d4e5f6-a7b8-9012-cdef-123456789012",
  pr4: "d4e5f6a7-b8c9-0123-def1-234567890123",
  pr5: "e5f6a7b8-c9d0-1234-ef12-345678901234",
  pr6: "f6a7b8c9-d0e1-2345-f123-456789012345",
  pr7: "a7b8c9d0-e1f2-3456-1234-567890123456",
  pr8: "b8c9d0e1-f2a3-4567-2345-678901234567",
  pr9: "c9d0e1f2-a3b4-5678-3456-789012345678",
  pr10: "d0e1f2a3-b4c5-6789-4567-890123456789",
};

export const dummyProjects = [
  {
    id: projectIds.pr1,
    title: "E-Commerce Fullstack",
    description:
      "Platform belanja online dengan Next.js 16, Prisma 7, PostgreSQL, dan Midtrans payment gateway.",
    image: svgPlaceholder("E-Commerce"),
    tags: ["Next.js", "Prisma", "PostgreSQL"],
    author: "Ahmad Fauzi",
    authorImage: svgPlaceholder("AF", 100, 100),
    likes: 42,
    comments: 8,
  },
  {
    id: projectIds.pr2,
    title: "Donor Darah App",
    description:
      "Aplikasi darurat donor darah berbasis React Native + Firebase. Fitur Maps integration buat cari lokasi donor terdekat.",
    image: svgPlaceholder("Donor App"),
    tags: ["React Native", "Firebase", "Google Maps"],
    author: "Sari Dewi",
    authorImage: svgPlaceholder("SD", 100, 100),
    likes: 56,
    comments: 12,
  },
  {
    id: projectIds.pr3,
    title: "Dashboard Analytics",
    description:
      "Real-time dashboard analytics menggunakan React + D3.js + WebSocket. Menampilkan data penjualan secara live.",
    image: svgPlaceholder("Dashboard"),
    tags: ["React", "D3.js", "WebSocket"],
    author: "Budi Santoso",
    authorImage: svgPlaceholder("BS", 100, 100),
    likes: 28,
    comments: 5,
  },
  {
    id: projectIds.pr4,
    title: "Sistem Parkir Otomatis",
    description:
      "IoT project: sistem parkir otomatis dengan sensor ultrasonic, ESP32, dan backend Node.js.",
    image: svgPlaceholder("IoT Parkir"),
    tags: ["IoT", "Node.js", "ESP32"],
    author: "Citra Lestari",
    authorImage: svgPlaceholder("CL", 100, 100),
    likes: 71,
    comments: 15,
  },
  {
    id: projectIds.pr5,
    title: "AI Image Generator",
    description:
      "Text-to-image generator menggunakan Stable Diffusion + FastAPI + React. Bisa generate gambar dari deskripsi teks.",
    image: svgPlaceholder("AI Generator"),
    tags: ["Python", "FastAPI", "React"],
    author: "Dimas Ardianto",
    authorImage: svgPlaceholder("DA", 100, 100),
    likes: 93,
    comments: 21,
  },
  {
    id: projectIds.pr6,
    title: "Clone Twitter dengan Go",
    description:
      "Backend Twitter clone menggunakan Go + Gin + PostgreSQL + Redis. Fitur: tweet, follow, timeline, notification.",
    image: svgPlaceholder("Go Backend"),
    tags: ["Go", "Gin", "Redis"],
    author: "Eko Prasetyo",
    authorImage: svgPlaceholder("EP", 100, 100),
    likes: 35,
    comments: 6,
  },
  {
    id: projectIds.pr7,
    title: "Aplikasi Cuaca Real-time",
    description:
      "Weather app dengan real-time data dari BMKG, pakai Next.js + Chart.js buat visualisasi cuaca mingguan.",
    image: svgPlaceholder("Weather App"),
    tags: ["Next.js", "Chart.js", "API"],
    author: "Fani Wijaya",
    authorImage: svgPlaceholder("FW", 100, 100),
    likes: 19,
    comments: 3,
  },
  {
    id: projectIds.pr8,
    title: "Platform Belajar Online",
    description:
      "LMS (Learning Management System) dengan Laravel + Vue.js + MySQL. Support video streaming dan quiz interaktif.",
    image: svgPlaceholder("LMS"),
    tags: ["Laravel", "Vue.js", "MySQL"],
    author: "Gilang Permana",
    authorImage: svgPlaceholder("GP", 100, 100),
    likes: 47,
    comments: 9,
  },
  {
    id: projectIds.pr9,
    title: "REST API Boilerplate",
    description:
      "Starter template REST API dengan Express + TypeScript + Prisma + JWT. Udah termasuk testing, validation, dan documentation.",
    image: svgPlaceholder("REST API"),
    tags: ["Express", "TypeScript", "Prisma"],
    author: "Hendra Gunawan",
    authorImage: svgPlaceholder("HG", 100, 100),
    likes: 62,
    comments: 14,
  },
  {
    id: projectIds.pr10,
    title: "Game 2D Platformer",
    description:
      "Game platformer 2D pakai Phaser.js + TypeScript. Ada 10 level, boss fight, dan leaderboard online.",
    image: svgPlaceholder("Phaser Game"),
    tags: ["Phaser.js", "TypeScript", "Canvas"],
    author: "Indah Permata",
    authorImage: svgPlaceholder("IP", 100, 100),
    likes: 84,
    comments: 18,
  },
];

export const dummyFeed = [
  {
    id: postIds.p1,
    name: "Ahmad Fauzi",
    username: "ahmadfauzi",
    time: "2 jam",
    content:
      "Baru aja selesai bikin project e-commerce fullstack pake Next.js + Prisma + Midtrans! Stack: Next.js 16, Prisma 7, PostgreSQL di Neon, Midtrans buat payment. Fitur: auth, cart, checkout, admin dashboard.",
    image: svgPlaceholder("Fullstack E-Commerce"),
    likes: 24,
    comments: 7,
    avatar: svgPlaceholder("AF", 100, 100),
  },
  {
    id: postIds.p2,
    name: "Sari Dewi",
    username: "saridevi",
    time: "5 jam",
    content:
      "Hari ini ikut hackathon! Kita bikin app donor darah darurat pake React Native + Firebase + Google Maps API. Seru banget kolaborasi dengan tim dari berbagai kota!",
    image: svgPlaceholder("Hackathon App"),
    likes: 56,
    comments: 12,
    avatar: svgPlaceholder("SD", 100, 100),
  },
  {
    id: postIds.p3,
    name: "Dimas Ardianto",
    username: "dimasardianto",
    time: "8 jam",
    content:
      "Akhirnya rilis AI Image Generator yang kubuat selama 2 bulan! Pake Stable Diffusion + FastAPI + React. Coba generate gambar dari teks, hasilnya lumayan. Masih open source, pull request welcome!",
    image: svgPlaceholder("AI Image Generator"),
    likes: 93,
    comments: 21,
    avatar: svgPlaceholder("DA", 100, 100),
  },
  {
    id: postIds.p4,
    name: "Eko Prasetyo",
    username: "ekopras",
    time: "1 hari",
    content:
      "Siapa yang nyari backend developer buat freelance? Gue bisa Go, Node.js, atau Python. Udah 3 tahun experience di backend, pernah handle system dengan 100k+ users.",
    likes: 8,
    comments: 34,
    avatar: svgPlaceholder("EP", 100, 100),
  },
  {
    id: postIds.p5,
    name: "Indah Permata",
    username: "indahpermata",
    time: "1 hari",
    content:
      "Game platformer 2D yang gue buat pake Phaser.js udh tembus 1000 download! Seneng banget lihat orang-orang mainin game kita. Next mau bikin versi mobile-nya 🤩",
    image: svgPlaceholder("Platformer Game"),
    likes: 84,
    comments: 18,
    avatar: svgPlaceholder("IP", 100, 100),
  },
];

export const dummyComments: Record<string, { name: string; username: string; avatar: string; time: string; content: string; likes: number }[]> = {
  [postIds.p1]: [
    {
      name: "Budi Santoso",
      username: "budisantoso",
      avatar: svgPlaceholder("BS", 100, 100),
      time: "1 jam",
      content: "Mantap bang! Stacknya lengkap banget. Midtransnya pake apa? Snap API atau Core API?",
      likes: 3,
    },
    {
      name: "Citra Lestari",
      username: "citralestari",
      avatar: svgPlaceholder("CL", 100, 100),
      time: "30 menit",
      content: "Keren! source codenya di GitHub? pengen belajar 🙏",
      likes: 5,
    },
    {
      name: "Ahmad Fauzi",
      username: "ahmadfauzi",
      avatar: svgPlaceholder("AF", 100, 100),
      time: "15 menit",
      content: "@budisantoso pake Snap API biar gampang. @citralestari iya, nanti aku push ke GitHub ya!",
      likes: 2,
    },
    {
      name: "Eko Prasetyo",
      username: "ekopras",
      avatar: svgPlaceholder("EP", 100, 100),
      time: "10 menit",
      content: "Next.js 16 udah stabil? aku masih pake 14 soalnya",
      likes: 1,
    },
    {
      name: "Fani Wijaya",
      username: "faniwijaya",
      avatar: svgPlaceholder("FW", 100, 100),
      time: "5 menit",
      content: "Gila keren banget sih! udah production?",
      likes: 4,
    },
    {
      name: "Gilang Permana",
      username: "gilangpermana",
      avatar: svgPlaceholder("GP", 100, 100),
      time: "2 menit",
      content: "Salut! next level banget ini 🔥",
      likes: 6,
    },
    {
      name: "Hendra Gunawan",
      username: "hendragunawan",
      avatar: svgPlaceholder("HG", 100, 100),
      time: "1 menit",
      content: "admin dashboardnya pake apa bang?",
      likes: 0,
    },
  ],
  [postIds.p2]: [
    {
      name: "Dimas Ardianto",
      username: "dimasardianto",
      avatar: svgPlaceholder("DA", 100, 100),
      time: "3 jam",
      content: "Wah keren banget! aku juga mau ikut hackathon next time. Timnya brp orang?",
      likes: 4,
    },
    {
      name: "Sari Dewi",
      username: "saridevi",
      avatar: svgPlaceholder("SD", 100, 100),
      time: "2 jam",
      content: "tim 4 orang! kita ada 1 UI/UX, 2 frontend, 1 backend. seru banget kolaborasinya",
      likes: 7,
    },
    {
      name: "Budi Santoso",
      username: "budisantoso",
      avatar: svgPlaceholder("BS", 100, 100),
      time: "1 jam",
      content: "Firebase pake free plan? kuat ga buat production?",
      likes: 1,
    },
    {
      name: "Indah Permata",
      username: "indahpermata",
      avatar: svgPlaceholder("IP", 100, 100),
      time: "45 menit",
      content: "React Native + Firebase itu powerful banget buat MVP 🤩",
      likes: 3,
    },
    {
      name: "Ahmad Fauzi",
      username: "ahmadfauzi",
      avatar: svgPlaceholder("AF", 100, 100),
      time: "30 menit",
      content: "donor darah app, nice! ini bakal berguna banget di Indonesia",
      likes: 8,
    },
  ],
  [postIds.p3]: [
    {
      name: "Ahmad Fauzi",
      username: "ahmadfauzi",
      avatar: svgPlaceholder("AF", 100, 100),
      time: "5 jam",
      content: "D3.js? bukan pake chart library lain? pengen coba D3 tapi keliatannya complex",
      likes: 2,
    },
    {
      name: "Dimas Ardianto",
      username: "dimasardianto",
      avatar: svgPlaceholder("DA", 100, 100),
      time: "4 jam",
      content: "D3.js emang complex tapi fleksibel banget. cocok buat custom visualization",
      likes: 5,
    },
    {
      name: "Eko Prasetyo",
      username: "ekopras",
      avatar: svgPlaceholder("EP", 100, 100),
      time: "2 jam",
      content: "WebSocket pake Socket.io atau native?",
      likes: 0,
    },
    {
      name: "Budi Santoso",
      username: "budisantoso",
      avatar: svgPlaceholder("BS", 100, 100),
      time: "1 jam",
      content: "Dashboardnya realtime ya? mantap buat monitoring",
      likes: 1,
    },
    {
      name: "Sari Dewi",
      username: "saridevi",
      avatar: svgPlaceholder("SD", 100, 100),
      time: "30 menit",
      content: "warna dashboardnya aesthetic! pake template apa?",
      likes: 3,
    },
  ],
  [postIds.p4]: [
    {
      name: "Hendra Gunawan",
      username: "hendragunawan",
      avatar: svgPlaceholder("HG", 100, 100),
      time: "12 jam",
      content: "IoT bang? keren! ESP32 langsung connect ke backend?",
      likes: 4,
    },
    {
      name: "Eko Prasetyo",
      username: "ekopras",
      avatar: svgPlaceholder("EP", 100, 100),
      time: "10 jam",
      content: "Ini bisa dipake buat parkir umum ga? kapan2 kita collab ya!",
      likes: 6,
    },
    {
      name: "Citra Lestari",
      username: "citralestari",
      avatar: svgPlaceholder("CL", 100, 100),
      time: "8 jam",
      content: "sensor ultrasonicnya pake HC-SR04?",
      likes: 2,
    },
  ],
  [postIds.p5]: [
    {
      name: "Indah Permata",
      username: "indahpermata",
      avatar: svgPlaceholder("IP", 100, 100),
      time: "4 jam",
      content: "WOAH Stable Diffusion! pake GPU apa buat trainingnya?",
      likes: 8,
    },
    {
      name: "Dimas Ardianto",
      username: "dimasardianto",
      avatar: svgPlaceholder("DA", 100, 100),
      time: "3 jam",
      content: "pake model fine-tuning juga atau langsung pretrained?",
      likes: 3,
    },
    {
      name: "Ahmad Fauzi",
      username: "ahmadfauzi",
      avatar: svgPlaceholder("AF", 100, 100),
      time: "2 jam",
      content: "repo-nya di GitHub? mau ikut contribute!",
      likes: 5,
    },
    {
      name: "Sari Dewi",
      username: "saridevi",
      avatar: svgPlaceholder("SD", 100, 100),
      time: "1 jam",
      content: "generatenya lama ga? pake GPU mana?",
      likes: 1,
    },
    {
      name: "Fani Wijaya",
      username: "faniwijaya",
      avatar: svgPlaceholder("FW", 100, 100),
      time: "30 menit",
      content: "AI Image Generator itu next level banget! salut 🔥",
      likes: 4,
    },
  ],
};
